"""Exemplars of the database schemas"""
EXEMPLARS = {'abstracts': {'_id': 'Mouginot.Model',
                           'coauthors': 'P.P.H. Wilson',
                           'email': 'mouginot@wisc.edu',
                           'firstname': 'Baptiste',
                           'institution': 'University of Wisconsin-Madison',
                           'lastname': 'Mouginot',
                           'references': '[1] B. MOUGINOT, “cyCLASS: CLASS models for Cyclus,”, Figshare, https://dx.doi.org/10.6084/m9.figshare.3468671.v2 (2016).',
                           'text': 'The CLASS team has developed high quality predictors based on pre-trained neural network...',
                           'timestamp': '5/5/2017 13:15:59',
                           'title': 'Model Performance Analysis'},
             'assignments': {'_id': 'hw01-rx-power',
                             'category': 'homework',
                             'courses': ['EMCH-558-2016-S',
                                         'EMCH-758-2016-S'],
                             'points': [1, 2, 3],
                             'questions': ['1-9', '1-10', '1-12']},
             'blog': {'_id': 'my-vision',
                      'author': 'Anthony Scopatz',
                      'day': 18,
                      'month': 'September',
                      'original': 'https://scopatz.com/my-vision/',
                      'post': 'I would like see things move forward. Deep, I know!',
                      'title': 'My Vision',
                      'year': 2015},
             'citations': {'_id': 'meurer2016sympy',
                           'author': ['Meurer, Aaron',
                                      'Smith, Christopher P',
                                      'Paprocki, Mateusz',
                                      "{\\v{C}}ert{\\'\\i}k, Ond{\\v{r}}ej",
                                      'Rocklin, Matthew',
                                      'Kumar, AMiT',
                                      'Ivanov, Sergiu',
                                      'Moore, Jason K',
                                      'Singh, Sartaj',
                                      'Rathnayake, Thilina',
                                      'Sean Vig',
                                      'Brian E Granger',
                                      'Richard P Muller',
                                      'Francesco Bonazzi',
                                      'Harsh Gupta',
                                      'Shivam Vats',
                                      'Fredrik Johansson',
                                      'Fabian Pedregosa',
                                      'Matthew J Curry',
                                      'Ashutosh Saboo',
                                      'Isuru Fernando',
                                      'Sumith Kulal',
                                      'Robert Cimrman',
                                      'Anthony Scopatz'],
                           'entrytype': 'article',
                           'journal': 'PeerJ Computer Science',
                           'month': 'Jan',
                           'pages': 'e103',
                           'publisher': 'PeerJ Inc. San Francisco, USA',
                           'title': 'SymPy: Symbolic computing in Python',
                           'volume': '4',
                           'year': '2017'},
             'courses': {'_id': 'EMCH-552-2016-F',
                         'active': False,
                         'department': 'EMCH',
                         'number': 552,
                         'scale': [[0.875, 'A'],
                                   [0.8125, 'B+'],
                                   [0.75, 'B'],
                                   [0.6875, 'C+'],
                                   [0.625, 'C'],
                                   [0.5625, 'D+'],
                                   [0.5, 'D'],
                                   [-1.0, 'F']],
                         'season': 'F',
                         'students': ['Human A. Person', 'Human B. Person'],
                         'syllabus': 'emch552-2016-f-syllabus.pdf',
                         'weights': {'class-notes': 0.15,
                                     'final': 0.3,
                                     'homework': 0.35,
                                     'midterm': 0.2},
                         'year': 2016},
             'grades': {
                 '_id': 'Human A. Person-rx-power-hw02-EMCH-758-2017-S',
                 'student': 'hap',
                 'assignment': '2017-rx-power-hw02',
                 'course': 'EMCH-758-2017-S',
                 'scores': [1, 1.6, 3]},
             'grants': {'_id': 'SymPy-1.1',
                        'amount': 3000.0,
                        'begin_day': 1,
                        'begin_month': 'May',
                        'begin_year': 2017,
                        'call_for_proposals': 'https://groups.google.com/d/msg/numfocus/wPjhdm8NJiA/S8JL1_NZDQAJ',
                        'end_day': 31,
                        'end_month': 'December',
                        'end_year': 2017,
                        'funder': 'NumFOCUS',
                        'narrative': 'https://docs.google.com/document/d/1nZxqoL-Ucni_aXLWmXtRDd3IWqW0mZBO65CEvDrsXZM/edit?usp=sharing',
                        'program': 'Small Development Grants',
                        'team': [
                            {'institution': 'University of South Carolina',
                             'name': 'Anthony Scopatz',
                             'position': 'PI'},
                            {'institution': 'University of South Carolina',
                             'name': 'Aaron Meurer',
                             'position': 'researcher'}],
                        'title': 'SymPy 1.1 Release Support'},
             'jobs': {'_id': '0004',
                      'background_fields': ['Data Science',
                                            'Data Engineering',
                                            'Computer Engineering',
                                            'Computer Science',
                                            'Applied Mathematics',
                                            'Physics',
                                            'Nuclear Engineering',
                                            'Mechanical Engineering',
                                            'Or similar'],
                      'compensation': [
                          'Salary and compensation will be based on prior work experience.'],
                      'contact': 'Please send CV or resume to Prof. Scopatz at scopatzATcec.sc.edu.',
                      'day': 1,
                      'description': '<p>We are seeking a dedicated individual to help to aid in ...',
                      'month': 'July',
                      'open': False,
                      'positions': ['Scientific Software Developer',
                                    'Programmer'],
                      'start_date': 'ASAP',
                      'title': 'Open Source Scientific Software Maintainer',
                      'year': 2015},
             'news': {'_id': '56b4eb6d421aa921504ef2a9',
                      'author': 'Anthony Scopatz',
                      'body': 'Dr. Robert Flanagan joined ERGS as a post-doctoral scholar.',
                      'day': 1,
                      'month': 'February',
                      'year': 2016},
             'people': {'_id': 'scopatz',
                        'aka': ['Scopatz',
                                'Scopatz, A',
                                'Scopatz, A.',
                                'Scopatz, A M',
                                'Anthony Michael Scopatz'],
                        'avatar': 'https://avatars1.githubusercontent.com/u/320553?v=3&s=200',
                        'bio': 'Anthony Scopatz is currently an Assistant Professor',
                        'education': [{'begin_year': 2008,
                                       'degree': 'Ph.D. Mechanical Engineering, Nuclear and Radiation Engineering Program',
                                       'end_year': 2011,
                                       'institution': 'The University of Texas at Austin',
                                       'location': 'Austin, TX',
                                       'other': [
                                           'Adviser: Erich A. Schneider',
                                           'Dissertation: Essential Physics for Fuel Cycle Modeling & Analysis']},
                                      {'begin_year': 2006,
                                       'degree': 'M.S.E. Mechanical Engineering, Nuclear and Radiation Engineering Program',
                                       'end_year': 2007,
                                       'institution': 'The University of Texas at Austin',
                                       'location': 'Austin, TX',
                                       'other': [
                                           'Adviser: Erich A. Schneider',
                                           'Thesis: Recyclable Uranium Options under the Global Nuclear Energy Partnership']},
                                      {'begin_year': 2002,
                                       'degree': 'B.S. Physics',
                                       'end_year': 2006,
                                       'institution': 'University of California, Santa Barbara',
                                       'location': 'Santa Barbara, CA',
                                       'other': [
                                           'Graduated with a Major in Physics and a Minor in Mathematics']}],
                        'email': 'scopatz@cec.sc.edu',
                        'employment': [{'begin_year': 2015,
                                        'location': 'Columbia, SC',
                                        'organization': 'The University of South Carolina',
                                        'other': [
                                            'Cyclus: An agent-based, discrete time nuclear fuel cycle simulator.',
                                            'PyNE: The Nuclear Engineering Toolkit.',
                                            'Website: http://www.ergs.sc.edu/'],
                                        'position': 'Assistant Professor, Mechanical Engineering Department'},
                                       {'begin_year': 2013,
                                        'end_year': 2015,
                                        'location': 'Madison, WI',
                                        'organization': 'CNERG, The University of Wisconsin-Madison',
                                        'other': [
                                            'Cyclus: An agent-based, discrete time nuclear fuel cycle simulator.',
                                            'PyNE: The Nuclear Engineering Toolkit.',
                                            'Website: https://cnerg.github.io/'],
                                        'position': 'Associate Scientist, Engineering Physics Department'},
                                       {'begin_month': 'Nov',
                                        'begin_year': 2011,
                                        'end_month': 'May',
                                        'end_year': 2013,
                                        'location': 'Chicago, IL',
                                        'organization': 'The FLASH Center, The University of Chicago',
                                        'other': [
                                            'NIF: Simulation of magnetic field generation from neutral plasmas using FLASH.',
                                            'CosmoB: Simulation of magnetic field generation from neutral plasmas using FLASH.',
                                            'FLASH4: High-energy density physics capabilities and utilities.',
                                            'Simulated Diagnostics: Schlieren, shadowgraphy, Langmuir probes, etc. from FLASH.',
                                            'OpacPlot: HDF5-based equation of state and opacity file format.',
                                            'Website: http://flash.uchicago.edu/site/'],
                                        'position': 'Research Scientist, Postdoctoral Scholar'}],
                        'funding': [
                            {'name': "Omega Laser User's Group Travel Award",
                             'value': 1100,
                             'year': 2013},
                            {
                                'name': "NIF User's Group Travel Award",
                                'value': 1150,
                                'year': 2013}],
                        'membership': [{'begin_year': 2006,
                                        'organization': 'American Nuclear Society',
                                        'position': 'Member'},
                                       {'begin_year': 2013,
                                        'organization': 'Python Software Foundation',
                                        'position': 'Fellow'}],
                        'name': 'Anthony Scopatz',
                        'position': 'professor',
                        'skills': [{'category': 'Programming Languages',
                                    'level': 'expert',
                                    'name': 'Python'},
                                   {
                                       'category': 'Programming Languages',
                                       'level': 'expert',
                                       'name': 'Cython'}],
                        'teaching': [{
                            'course': 'EMCH 552: Intro to Nuclear Engineering',
                            'description': 'This course is an introduction to nuclear physics.',
                            'month': 'August',
                            'organization': 'University of South Carolina',
                            'position': 'Professor',
                            'syllabus': 'https://drive.google.com/open?id=0BxUpd34yizZreDBCMEJNY2FUbnc',
                            'year': 2017},
                            {
                                'course': 'EMCH 558/758: Reactor Power Systems',
                                'description': 'This course covers conventional reactors.',
                                'month': 'January',
                                'organization': 'University of South Carolina',
                                'position': 'Professor',
                                'syllabus': 'https://docs.google.com/document/d/1uMAx_KFZK9ugYyF6wWtLLWgITVhaTBkAf8-PxiboYdM/edit?usp=sharing',
                                'year': 2017}],
                        'title': 'Dr.'},
             'projects': {'_id': 'Cyclus',
                          'name': 'Cyclus',
                          'description': 'Agent-Based Nuclear Fuel Cycle Simulator',
                          'logo': 'http://fuelcycle.org/_static/big_c.png',
                          'other': [
                              'Discrete facilities with discrete material transactions',
                              'Low barrier to entry, rapid payback to adoption'],
                          'repo': 'https://github.com/cyclus/cyclus/',
                          'team': [{'begin_month': 'June',
                                    'begin_year': 2013,
                                    'end_month': 'July',
                                    'end_year': 2015,
                                    'name': 'Anthony Scopatz',
                                    'position': 'Project Lead'}],
                          'website': 'http://fuelcycle.org/'},
             'proposals': {'_id': 'mypropsal',
                           'ammount': 1000000.0,
                           'authors': ['Anthony Scopatz',
                                       'Robert Flanagan'],
                           'currency': 'USD',
                           'day': 18,
                           'durration': 3,
                           'full': {
                               'benefit_of_collaboration': 'http://pdf.com/benefit_of_collaboration',
                               'cv': [
                                   'http://pdf.com/scopatz-cv',
                                   'http://pdf.com/flanagan-cv'],
                               'narrative': 'http://some.com/pdf'},
                           'month': 'Aug',
                           'pi': 'Anthony Scopatz',
                           'pre': {
                               'benefit_of_collaboration': 'http://pdf.com/benefit_of_collaboration',
                               'cv': [
                                   'http://pdf.com/scopatz-cv',
                                   'http://pdf.com/flanagan-cv'],
                               'day': 2,
                               'month': 'Aug',
                               'narrative': 'http://some.com/pdf',
                               'year': 1998},
                           'status': 'submitted',
                           'title': 'A very fine proposal indeed',
                           'year': 1999},
             'students': {'_id': 'Human A. Person',
                          'aka': ['H. A. Person'],
                          'email': 'haperson@uni.edu',
                          'university_id': 'HAP42'}}
