"""Database schemas"""
schemas = {
    'grants': {
        '_id':
            {'description': 'short represntation, such as this-is-my-name',
             'required': True,
             'type': (str, int, float)},
        'amount': {'description': 'value of award',
                   'required': True,
                   'type': (int, float)},
        'begin_day': {'description': 'start day of the grant',
                      'required': False,
                      'type': int},
        'begin_month': {'description': 'start month of the grant',
                        'required': True,
                        'type': str},
        'begin_year': {'description': 'start year of the grant',
                       'required': True,
                       'type': int},
        'benefit_of_collaboration': {'description': '',
                                     'required': False,
                                     'type': str},
        'call_for_proposals': {'description': '',
                               'required': False,
                               'type': str},
        'currency': {'description': "typically '$' or 'USD'",
                     'required': False,
                     'type': str},
        'end_day': {'description': 'end day of the grant',
                    'required': False,
                    'type': (str, int)},
        'end_month"': {'description': 'end month of the grant',
                       'required': False,
                       'type': str},
        'end_year': {'description': 'end year of the grant',
                     'required': True,
                     'type': int},
        'funder': {'description': 'the agency funding the work',
                   'required': True,
                   'type': str},
        'grant_id': {'description': 'the identfier for this work',
                     'required': False,
                     'type': str},
        'narrative': {
            'description': '',
            'required': False,
            'type': str},
        'program': {'description': 'the program the work was funded under',
                    'required': True,
                    'type': str},
        'team': {
            'description': 'information about the team members participating '
                           'in the grant.', 
            'required': True,
            'type': {'cv': {'required': False, 'type': str},
                     'institution': {'required': True, 'type': str},
                     'name': {'required': True, 'type': str},
                     'position': {'required': True, 'type': str},
                     'subaward_amount': {
                         'required': False,
                         'type': (int, float)}}},
        'title': {'description': 'actual title of proposal / grant',
                  'required': True,
                  'type': str}},
    'abstracts': {
        '_id': {
            'description': 'Unique identifier for submission. This generally '
                           'includes the author name and part of the title.', 
            'required': True,
            'type': str},
        'coauthors': {'description': 'names of coauthors',
                      'required': False,
                      'type': str},
        'email': {'description': 'contact email for the author.',
                  'required': True,
                  'type': str},
        'firstname': {'description': 'first name of the author.',
                      'required': True,
                      'type': str},
        'institution': {'description': 'name of the inistitution',
                        'required': True,
                        'type': str},
        'lastname': {'description': 'last name of the author.',
                     'required': True,
                     'type': str},
        'references': {
            'description': 'HTML string of reference for the abstract itself',
            'required': False,
            'type': str},
        'text': {'description': 'HTML string of the abstract.',
                 'required': True,
                 'type': str},
        'timestamp': {
            'description': 'The time when the abstract was submitted.',
            'required': True,
            'type': str},
        'title': {'description': 'title of the presentation/paper.',
                  'required': True,
                  'type': str}},
    'blog': {
        '_id': {'description': 'short represntation, such as this-is-my-title',
                'required': True,
                'type': str},
        'author': {'description': 'name or AKA of author',
                   'required': True,
                   'type': str},
        'day': {
            'description': 'Publication day',
            'required': True,
            'type': int},
        'month': {
            'description': 'Publication month',
            'required': True,
            'type': str},
        'original': {
            'description': 'URL of original post, if this is a repost',
            'required': False,
            'type': str},
        'post': {'description': 'actual contents of the post',
                 'required': True,
                 'type': str},
        'title': {'description': 'full human readable title',
                  'required': True,
                  'type': str},
        'year': {
            'description': 'Publication year',
            'required': True,
            'type': int}},
    'grades': {
        '_id': {
            'description': 'unique id, typically the '
                           'student-assignment-course',
            'required': True,
            'type': str},
        'assignment': {
            'description': 'assignment id',
            'required': True,
            'type': str},
        'course': {'description': 'course id', 'required': True, 'type': str},
        'filename': {'description': 'path to file in store',
                     'required': False,
                     'type': str},
        'scores': {
            'description': 'the number of points earned on each question',
            'required': True,
            'type': (int, float)},
        'student': {
            'description': 'student id',
            'required': True,
            'type': str}},
    'assignments': {
        '_id': {
            'description': 'A unique id for the assignment, such a '
                           'HW01-EMCH-558-2016-S', 
            'required': True,
            'type': str},
        'category': {'description': "such as 'homework' or 'final'",
                     'required': True,
                     'type': str},
        'courses': {
            'description': 'ids of the courses that have this assignment',
            'required': True,
            'type': str},
        'file': {'description': 'path to assignment file in store',
                 'required': False,
                 'type': str},
        'points': {
            'description': 'list of number of points possible for each '
                           'question. Length is the number of questions', 
            'required': True,
            'type': (int, float)},
        'question': {
            'description': 'titles for the questions on this assignment',
            'required': False,
            'type': str},
        'solution': {'description': 'path to solution file in store',
                     'required': False,
                     'type': str}},
    'projects': {'_id': {'description': 'Unique project identifier.',
                         'required': True,
                         'type': str},
                 'description': {'description': 'brief project description.',
                                 'required': True,
                                 'type': str},
                 'logo': {'description': 'URL to the project logo',
                          'required': False,
                          'type': str},
                 'name': {'description': 'name of the project.',
                          'required': True,
                          'type': str},
                 'other': {
                     'description': 'other information about the project',
                     'required': False,
                     'type': str},
                 'repo': {
                     'description': 'URL of the source code repo, if available',
                     'required': False,
                     'type': str},
                 # XXX: FIXME
                 'team': {
                     'description': 'People who are/have been woking on this '
                                    'project.',
                     'required': True,
                     'type': {'begin_month': {'required': False, 'type': str},
                              'begin_year': {'required': True, 'type': int},
                              'end_month': {'required': False, 'type': str},
                              'end_year': {'required': False, 'type': int},
                              'name': {'required': True, 'type': str},
                              'position': {'required': True, 'type': str}}
                 },
                 'website': {'description': 'URL of the website.',
                             'required': True,
                             'type': str}},
    'proposals': {
        '_id': {'description': 'short represntation, such as this-is-my-name',
                'required': True,
                'type': (str, int, float)},
        'ammount': {'description': 'value of award',
                    'required': True,
                    'type': (int, float)},
        'authors': {'description': 'other investigator names',
                    'required': True,
                    'type': str},
        'currency': {'description': "typically '$' or 'USD'",
                     'required': True,
                     'type': str},
        'day': {'description': 'day that the proposal is due',
                'required': True,
                'type': int},
        'durration': {'description': 'number of years',
                      'required': True,
                      'type': (int, float)},
        'month': {'description': 'month that the proposal is due',
                  'required': True,
                  'type': str},
        'pi': {'description': 'principal investigator name',
               'required': True,
               'type': str},
        # XXX: FIXME
        'pre': {'description': 'Information about the pre-proposal',
                'required': False,
                'type': dict},
        'status': {'description': "e.g. 'submitted', 'accepted', 'rejected'",
                   'required': True,
                   'type': str},
        'title': {'description': 'actual title of proposal',
                  'required': True,
                  'type': str},
        'year': {'description': 'Year that the proposal is due',
                 'required': True,
                 'type': int}},
    'students': {
        '_id': {'description': 'short represntation, such as this-is-my-name',
                'required': True,
                'type': str},
        'aka': {'description': 'list of aliases',
                'required': False,
                'type': (list, str)},
        'email': {
            'description': 'email address',
            'required': False,
            'type': str},
        'university_id': {
            'description': 'The university identifier for the student',
            'required': False,
            'type': str}},
    'people': {'_id': {'description': 'unique identifier for the group member',
                       'required': True,
                       'type': str},
               'active': {
                   'description': 'If the person is an active member, '
                                  'default True.',
                   'required': False,
                   'type': bool},
               'aka': {
                   'description': 'list of aliases (also-known-as), useful '
                                  'for identifying the group member in '
                                  'citations or elsewhere.',
                   'required': True,
                   'type': str},
               'avatar': {
                   'description': 'URL to avatar',
                   'required': True,
                   'type': str},
               'bio': {'description': 'short biographical text',
                       'required': True,
                       'type': str},
               'collab': {
                   'description': 'If the person is a collaborator, default '
                                  'False.',
                   'required': False,
                   'type': bool},
               'education': {
                   'description': 'This contains the educational information '
                                  'for the group member.',
                   'required': True,
                   'type': {'begin_month': {'required': False, 'type': str},
                            'begin_year': {'required': True, 'type': int},
                            'degree': {'required': True, 'type': str},
                            'end_month': {'required': False, 'type': str},
                            'end_year': {'required': True, 'type': int},
                            'gpa': {'required': False, 'type': (float, str)},
                            'institution': {'required': True, 'type': str},
                            'location': {'required': True, 'type': str},
                            'other': {'required': False, 'type': str}}
               },
               'email': {'description': 'email address of the group member',
                         'required': False,
                         'type': str},
               'employment': {
                   'description': 'Employment information, similar to '
                                  'educational information.',
                   'required': True,
                   'type': {'begin_month': {'required': False, 'type': str},
                            'begin_year': {'required': True, 'type': int},
                            'end_month': {'required': False, 'type': str},
                            'end_year': {'required': False, 'type': int},
                            'location': {'required': True, 'type': str},
                            'organization': {'required': True, 'type': str},
                            'other': {'required': False, 'type': str},
                            'position': {'required': True, 'type': str}}},
               'funding': {
                   'description': 'Funding and scholarship that the group '
                                  'member has individually obtained in the '
                                  'past. **WARNING:** this is not to be '
                                  'confused with the **grants** collection',
                   'required': False,
                   'type': {'currency': {'required': False, 'type': str},
                            'duration': {'required': False, 'type': str},
                            'month': {'required': False, 'type': str},
                            'name': {'required': True, 'type': str},
                            'value': {'required': True, 'type': (float, int)},
                            'year': {'required': True, 'type': int}}
               },
               'honors': {
                   'description': 'Honors that have been awarded to this '
                                  'group member',
                   'required': False,
                   'type': {'description': {'required': False, 'type': str},
                            'month': {'required': False, 'type': str},
                            'name': {'required': True, 'type': str},
                            'year': {'required': True, 'type': int}}
               },
               'membership': {
                   'description': 'Profesional organizations this member is '
                                  'a part of',
                   'required': False,
                   'type': {'begin_month': {'required': False, 'type': str},
                            'begin_year': {'required': True, 'type': int},
                            'description': {'required': False, 'type': str},
                            'end_month': {'required': False, 'type': str},
                            'end_year': {'required': False, 'type': int},
                            'organization': {'required': True, 'type': str},
                            'position': {'required': True, 'type': str},
                            'website': {'required': False, 'type': str}}},
               'name': {'description': 'Full, canonical name for the person',
                        'required': True,
                        'type': str},
               'position': {
                   'description': 'such as professor, graduate student, '
                                  'or scientist',
                   'required': True,
                   'type': str},
               'service': {
                   'description': 'Service that this group member has provided',
                   'required': False,
                   'type': {'description': {'required': False, 'type': str},
                            'duration': {'required': False, 'type': str},
                            'month': {'required': False, 'type': str},
                            'name': {'required': True, 'type': str},
                            'year': {'required': True, 'type': int}}
               },
               'skills': {'description': 'Skill the group member has',
                          'required': False,
                          'type': {'category': {'required': True, 'type': str},
                                   'level': {'required': True, 'type': str},
                                   'name': {'required': True, 'type': str}}
                          },
               'teaching': {
                   'description': 'Courses that this group member has '
                                  'taught, if any',
                   'required': False,
                   'type': {'course': {'required': True, 'type': str},
                            'description': {'required': False, 'type': str},
                            'end_month': {'required': False, 'type': str},
                            'end_year': {'required': False, 'type': int},
                            'materials': {'required': False, 'type': str},
                            'month': {'required': False, 'type': str},
                            'organization': {'required': True, 'type': str},
                            'position': {'required': True, 'type': str},
                            'syllabus': {'required': False, 'type': str},
                            'video': {'required': False, 'type': str},
                            'website': {'required': False, 'type': str},
                            'year': {'required': True, 'type': int}}
               },
               'title': {'description': 'for example, Dr., etc.',
                         'required': False,
                         'type': str}
               }
}
