name: Check for News

on:
  pull_request_target:
    branches:
      - main  # GitHub does not evaluate expressions in trigger filters; edit this value if your base branch is not main

jobs:
  check-news-item:
    uses: scikit-package/release-scripts/.github/workflows/_check-news-item.yml@v0
    with:
      project: regolith
